# Generated by Django 2.0.7 on 2019-04-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanotask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hit',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='nanotask',
            name='project_name',
        ),
    ]
