# Generated by Django 2.0.4 on 2018-04-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanotask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nanotask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.TextField()),
                ('media_data', models.TextField(default={}, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanotask.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='template',
            name='project',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
