# Generated by Django 2.0.7 on 2019-04-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanotask', '0002_auto_20190402_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='amtassignment',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
