# Generated by Django 2.0.4 on 2018-04-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanotask', '0002_auto_20180408_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nanotask',
            name='project',
        ),
        migrations.AddField(
            model_name='nanotask',
            name='project_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
