# Generated by Django 2.0.7 on 2019-04-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanotask', '0003_amtassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='amtassignment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
