# Generated by Django 2.0.4 on 2018-04-09 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanotask', '0003_auto_20180408_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mturk_worker_id', models.CharField(default=None, max_length=255)),
                ('value', models.TextField(default=None)),
                ('nanotask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanotask.Nanotask')),
            ],
        ),
    ]
