# Generated by Django 2.0.7 on 2019-04-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanotask', '0004_amtassignment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amtassignment',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
