# Generated by Django 2.0.4 on 2018-04-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanotask', '0004_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='mturk_worker_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.TextField(default=None, null=True),
        ),
    ]
