# Generated by Django 2.0.7 on 2019-05-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanotask', '0005_auto_20190407_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanotask',
            name='instance_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
