# Generated by Django 2.0.7 on 2019-05-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanotask', '0006_nanotask_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='instance_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
