# Generated by Django 2.0.7 on 2019-10-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanotask', '0008_auto_20191010_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='test_score',
            field=models.FloatField(default=0.0),
        ),
    ]
